### ISSUE TITLE
The component does not work on safari (iOS)

### ISSUE THREAD

**Issue by leosok** [dmnWebDesign/vue-fb-customer-chat#11]
Hi,
great component, but there is an issue on iOS. Users and Browserstack are consistent about it. I tried your own site, https://dmnwebdesign.github.io/vue-fb-customer-chat/, too. The code from Facebook itself works. I am guessing that you use a version of the SDK which is not the most actual one!
Keep up the good work,
Leo

**Comment by leosok** [comment]
I looked into your code: you're loading SDK ` version: 'v3.0'` facebook now uses  `version: 'v5.0'`. I proposed the change.

**Comment by dmnCodes** [comment]
Hi @leosok,
thx for your comment. I've just upgraded SDK Version, but I'm not sure it help in your problem.

**Comment by leosok** [comment]
@dmnWebDesign, you are right. It's a messenger Bug. A very strange one: when you open a link from inside the Facebook Messenger App (it opens a browser which I suppose is a Web-View) it would not show the Messenger-Chat-Bubble. In a normal Browser Window it worked all the way. But because I sent the link to my friends via messenger they didn't see it. Maybe something to mention in the Docs?
Nevertheless good thing to update the SDK. 
(Issue can be closed!)
