### ISSUE TITLE
chatbox cannot be seen, even in the official demo page

### ISSUE THREAD

**Issue by oyilmaztekin** [dmnWebDesign/vue-fb-customer-chat#31]
Even in the [official demo page](https://dmnwebdesign.github.io/vue-fb-customer-chat/), nothing is showing up.  When I checked on developer tools, there is no FB object on the global, no attached element on the DOM either. Also, no error is seen on the console.

**Comment by joaquinmautone** [comment]
Same problem. I installed it yesterday and it worked fine, but today is broken.

**Comment by dmnCodes** [comment]
Plugin works fine, maybe that was Messenger problems.
