### ISSUE TITLE
Message not sent for Guest user

### ISSUE THREAD

**Issue by patrickboulay** [dmnWebDesign/vue-fb-customer-chat#32]
When I try to send a message as a Guest user, I got an error: This message didn't send

I read that is something about a webhook from Facebook page:
https://developers.facebook.com/docs/messenger-platform/discovery/facebook-chat-plugin#optional--handle-the-messaging-referrals-event-for-existing-conversations

Is it something that can be fixed or its a configuration in Messenger settings?

**Comment by patrickboulay** [comment]
Anyone already face this problem?

**Comment by dmnCodes** [comment]
That's probably Messenger problems.
